source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'JTBaseViewController_Example' do
  pod 'JTBaseViewController', :path => '../'

  target 'JTBaseViewController_Tests' do
    inherit! :search_paths

    
  end
end
